### ISSUE TITLE
comments in .ember-cli cause plugin to not detect pods

### ISSUE THREAD

**Issue by mattmarcum** [KatalysatorAB/atom-ember-tabs#1]
ember-pods-project#checkDotEmberCliFile was throwing an error trying to parse my .ember-cli file...the file had some multiline comments in it that came straight from ember-cli's blueprints, using ember-cli 1.13.8

If anyone else is having this problem delete the comments from your .ember-cli file

**Comment by erkie** [comment]
Thanks for reporting this! Will push a fix ASAP
