### ISSUE TITLE
Broken after updating to v2.40 on Atom v1.12.7

### ISSUE THREAD

**Issue by billdami** [KatalysatorAB/atom-ember-tabs#14]
After updating to the latest version of ember-tabs and the latest version of Atom, it appears that this package has stopped working, as I now see just "component.js", "template.hbs", ect as the tab names. Tested on multiple ember projects running different versions of ember/ember-cli, including one project running on ember/ember-cli v2.10. Tried restarting Atom, disabling/enabling/re-installing the package, but to no avail. I am running Atom on OSX 10.11.5. I also have not seen any errors in the Developer Tools console coming from ember-tabs.

Here's one of my .ember-cli files:
```
{
  /**
    Ember CLI sends analytics information by default. The data is completely
    anonymous, but there are times when you might want to disable this behavior.

    Setting `disableAnalytics` to true will prevent any data from being sent.
  */
  "disableAnalytics": false,
  "usePods": true
}
```

In all cases, the root project folder is the ember application directory itself. 

If you need any additional info, let me know.

**Comment by erkie** [comment]
@billdami thanks for reporting this! I have pushed a fix for this that should cause it to activate properly. Can you verify, and re-open if the issue still persists?
