### ISSUE TITLE
Recent update broke

### ISSUE THREAD

**Issue by haveanicedavid** [KatalysatorAB/atom-ember-tabs#6]
I wish I could give more constructive feedback, but the most recent update has broken the plugin for me - all files are being displayed as just the file (ex 'controller.js') - which is worse than even the default Atom settings as if I have multiple files open, they all are displayed the same (ex two controllers open would mean two 'controller.js' tabs)

**Comment by erkie** [comment]
@haveanicedavid  Dangit! Can you paste the contents of your `.ember-cli` file?

**Comment by haveanicedavid** [comment]
@erkie : 
{
  /**
    Ember CLI sends analytics information by default. The data is completely
    anonymous, but there are times when you might want to disable this behavior.

```
Setting `disableAnalytics` to true will prevent any data from being sent.
```

  */
  "disableAnalytics": false,
  "usePods": true
}

**Comment by erkie** [comment]
@haveanicedavid do you have a none-default `podModulePrefix`?

**Comment by haveanicedavid** [comment]
@erkie I do not. Do I need to set this in my environment.js? I'm very new to ember...

**Comment by erkie** [comment]
@haveanicedavid can you try installing `2.1.2` and see if it works? Close the issue if it does. Thanks!

**Comment by haveanicedavid** [comment]
@erkie I installed 2.1.2, but it doesn't seem to have had any effect. Same issue as before. Is there anything I can do to help troubleshoot?

**Comment by erkie** [comment]
@haveanicedavid Just to be sure, did you restart atom after the update? The old version did not clean up after itself properly...

**Comment by haveanicedavid** [comment]
@erkie I restarted Atom, restarted my computer, and did an uninstall / reinstall, all to no avail :(

It was working correctly in a previous version (assuming I didn't split panes), and only broke with the recent update.

**Comment by erkie** [comment]
@haveanicedavid  I identified some places that could cause the project to not load properly. Can you update to `2.1.3` and check if it works?

**Comment by haveanicedavid** [comment]
@erkie Unfortunately it's still not working :( 
<img width="802" alt="screen shot 2015-11-12 at 10 47 34 pm" src="https://cloud.githubusercontent.com/assets/9052511/11139670/7a435ec0-898f-11e5-8564-8f2f8bfcada6.png">

**Comment by erkie** [comment]
@haveanicedavid  Can you open the console and see what message you are getting there? cmd+shift+i (or View > Developer > Toggle Developer Tools) and press the Console tab. You should see some messages with [ember-tabs] prefixed. That would help a lot!

**Comment by omjrt88** [comment]
Hello @erkie , I'm having the same issue. I did show the Console tab, and this was the result: 

"[ember-tabs] Tried to open file pane. Open file pane failed."

This console error message was being display it from this code line: tabWatcher.isEmberPackagePath(activePath) 
(https://github.com/KatalysatorAB/atom-ember-tabs/blob/master/lib/ember-tabs.coffee#L66)

Did you know what is causing this on False??

Thanks,

**Comment by erkie** [comment]
@omjrt88  What is the full path of the file you tried to open the file pane on? And can you attach a screenshot of the entire console window here? Thanks!

**Comment by omjrt88** [comment]
Sure:

<img width="1440" alt="screen shot 2015-11-13 at 10 14 42 am" src="https://cloud.githubusercontent.com/assets/6087761/11150799/6deef296-89ef-11e5-8cd8-68051fb0f59f.png">

**Comment by erkie** [comment]
@omjrt88 I can't see anything that might indicate that it doesn't work. I have updated to 2.1.4, can you install that and restart Atom, and try it out, and then post a screenshot of the log again?

Thanks

**Comment by omjrt88** [comment]
There it is:

<img width="1440" alt="screen shot 2015-11-13 at 10 39 29 am" src="https://cloud.githubusercontent.com/assets/6087761/11151477/e6d28c6a-89f2-11e5-82cd-30d0a50d442d.png">

**Comment by omjrt88** [comment]
I think is comparing against other directory... Could be the ember version?

╰─➤  ember -v
version: 1.13.8
node: 0.12.2
npm: 2.13.4
os: darwin x64

There it is my ember version.

**Comment by erkie** [comment]
@omjrt88 I published a new version that should fix the issue. Can you check and verify?

**Comment by omjrt88** [comment]
Thanks dude! That's better! It's working now..

**Comment by erkie** [comment]
@omjrt88 awesome! Closing

**Comment by haveanicedavid** [comment]
Works for me too! Thanks, @erkie
